### ISSUE TITLE
Issue in Loading text classification mdoel

### ISSUE THREAD

**Issue by pooya-mohammadi** [hezarai/hezar#67]
![Screenshot from 2023-08-05 14-04-54](https://github.com/hezarai/hezar/assets/55460936/5e80b3c3-df54-484f-9748-3d81104355fd)

**Comment by arxyzan** [comment]
@pooya-mohammadi 
The name `normalizer` was changed to `text_normalizer` so that it wouldn't conflict with image or audio normalizers.
I'll check if the latest changes are included in the latest release.

**Comment by arxyzan** [comment]
I pushed a new release  (https://github.com/hezarai/hezar/releases/tag/0.20.1) and it should work fine now.
@pooya-mohammadi

**Comment by pooya-mohammadi** [comment]
![Screenshot from 2023-08-05 15-11-27](https://github.com/hezarai/hezar/assets/55460936/294bc2d0-5366-403c-af89-a343531c611f)
@arxyzan jan, the issue is not fixed!

**Comment by arxyzan** [comment]
Okay I got it. The problem was that the normalizer config on the hub was registered by the name `normalizer`. I changed it manually and it should work now.
@pooya-mohammadi
